### ISSUE TITLE
Content Type

### ISSUE THREAD

**Issue by bitblower** [softius/php-cross-domain-proxy#13]
Very useful bit of code, thanks.

I am having an issue with making a request via the proxy though when using a CONTENT_TYPE of 'json/application'. 

This fixed it:

```
foreach ( $_SERVER as $key => $value ) {
if ($key == 'CONTENT_TYPE')     
        $request_headers[] = "Content-Type: $value";
    elseif ( substr( $key, 0, 5 ) == 'HTTP_' )
```

**Comment by softius** [comment]
This is related to #11 and #12

**Comment by softius** [comment]
Thank you @bitblower . Recent code changes include this fix.
