### ISSUE TITLE
Integrating with Ajax

### ISSUE THREAD

**Issue by dpcarlton** [softius/php-cross-domain-proxy#14]
Not sure if this is the right place for this type of question, but I could not figure out another way to ask it.

I am moifying someone else' code to use a different url, but this URL is returing the error "No 'Access-Control-Allow-Origin' header is present on the requested resource".

I would like to try to use your code to proxy the following bit. I am wondering if you could provide some insight on how to use your code with this piece.

        $.ajax({
                type: 'GET',
                url: 'https://api.forecast.io/forecast/3a56a2a604c59597ec94f2ada341e263/38.8673,-104.7607?exclude=minutely,flags,hourly,alerts,
                success: function (data) {

The full source is here.

http://pastebin.com/1Wsi6HXM

**Comment by softius** [comment]
Hey @dpcarlton this is mentioned in README file.You can either:
* change the requested URL to proxy url (i.e. http://example.com/proxy.php) and the pass everything as parameters to proxy.php. Your AJAX url will be the `csurl` to proxy.php
* use ajaxPrefilter to auto-magic-ally make these changes for you. Very convenient for GET and POST requests.
