### ISSUE TITLE
Wrong content-length passed to cross domain URL

### ISSUE THREAD

**Issue by bonny** [softius/php-cross-domain-proxy#16]
When header `Content-Length` exists in the call to `proxy.php` then it's forwarded to the URL specified in `csurl`.

The length can however be wrong if using `post` as the method, since `csurl` can be in the data sent to `proxy.php`. The script removes `csurl` from the parameters, and then the length argument is off by the same number of chars as the url length.

Not sure how to be solve this. Maybe check if `Content-Length` is set and then decrease it by the string length of `csurl`. Anyway, I solved it by removing the header like this:

```
$request_headers = array_filter($request_headers, function($val) {
    return strpos($val, "Content-Length:") === false;
});
```

**Comment by softius** [comment]
Hi @bonny, I am not sure whether removing the header is the right solution here, as I would like to avoid limit the modifications to the original request.

Nevertheless, it's still possible to pass the `csurl` without using the POST body. 1) Use `HTTP_X_PROXY_URL` or 2) Append `?csurl=your-url-here` to POST URL

Hope the above helps.
