### ISSUE TITLE
missing session

### ISSUE THREAD

**Issue by davidmeirlevy** [softius/php-cross-domain-proxy#9]
the proxy doesn't pass the session (if exists), looks like for both ways.
session_start() didn't make it work..

**Comment by softius** [comment]
This an old comment but I am replying anyway for future reference.

This wont work (using session_start) .

Sessions are usually identified by Cookies (PHPSESSID) . This is stored in `$_SERVER['HTTP_COOKIE']` which is parsed and sent to remote URL as `Cookie` header.
